database:
  driverClass: org.postgresql.Driver
  url: jdbc:postgresql://postgres:5432/openregister_java
  user: postgres
  password:

  #db connection properties
  initialSize: 1
  minSize: 1
  maxSize: 4

  properties:
    charSet: UTF-8

server:
  registerDefaultExceptionMappers: false
  adminConnectors:
    - type: http
      port: 9092
  requestLog:
    appenders:
      - type: access-logstash-console

registerDomain: openregister.local:8080

register: country
schema: country

enableDownloadResource: true

externalConfigDirectory: /tmp

downloadConfigs: true

# can be http: file s3: or classpath: url
fieldsYamlLocation: http://field/records.yaml?page-size=5000
registersYamlLocation: http://register/records.yaml?page-size=5000

credentials:
  user: foo
  password: bar

# Logging settings.
logging:
  level: INFO
  # Logger-specific levels.
  loggers:
    "uk.gov": DEBUG
    "org.skife.jdbi.v2": TRACE
  appenders:
    - type: logstash-console

registers:
  territory:
    credentials:
      user: foo
      password: bar
    schema: territory
