ALTER TABLE entry ALTER COLUMN key SET NOT NULL;
ALTER TABLE entry ALTER COLUMN "timestamp" SET NOT NULL;

ALTER TABLE entry_item ALTER COLUMN entry_number SET NOT NULL;
ALTER TABLE entry_item ALTER COLUMN sha256hex SET NOT NULL;


