---
applications:
- name: alpha-basic
  memory: 2GB
  instances: 2
  buildpack: java_buildpack
  health-check-type: http
  health-check-http-endpoint: /healthcheck
  path: ../../openregister-java.jar
  domains:
    - alpha.openregister.org
  hosts:
    - datatype
    - field
    - register
  services:
    - alpha-db
    - logit-ssl-drain
  env:
    JBP_CONFIG_JAVA_MAIN: '{ arguments: "server s3://openregister.alpha.config/basic/openregister/paas-config.yaml" }'
    JBP_CONFIG_OPEN_JDK_JRE: '{ jre: { version: 11.+ } }'
    AWS_ACCESS_KEY_ID: change-me
    AWS_SECRET_ACCESS_KEY: change-me
    AWS_REGION: eu-west-1
